spring:
  application:
    name: paymentDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 补全了 characterEncoding=utf-8 并确保了时区设置正确
    url: jdbc:mysql://localhost:3306/payment_demo?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090

#mp-plus配置
mybatis-plus:
  configuration:
    # SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/paymentdemo/mapper/xml/*.xml